LibraryManagement/Controllers/PropController.cs
using LibraryManagement.Data.Interfaces;
using LibraryManagement.Data.Model;
using LibraryManagement.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryManagement.Controllers
{
    public class PropController : Controller
    {
        private readonly IPropRepository _propRepository;
        private readonly IOwnerRepository _ownerRepository;

        public PropController(IPropRepository propRepository, IOwnerRepository ownerRepository)
        {
            _propRepository = propRepository;
            _ownerRepository = ownerRepository;
        }

        [Route("Property")]
        public IActionResult List(int? ownerId, int? rentId)
        {
            if (ownerId == null && rentId == null)
            {
                // show all props
                var props = _propRepository.GetAllWithOwner();
                // check props
                return CheckProps(props);
            }
            else if (ownerId != null)
            {
                // filter by author id
                var owner = _ownerRepository
                    .GetWithProps((int)ownerId);

                // check author props
                if (owner.Props.Count() == 0)
                {
                    return View("OwnerEmpty", owner);
                }
                else
                {
                    return View(owner.Props);
                }
            }
            else if (rentId != null)
            {
                // filter by borrower id
                var props = _propRepository
                    .FindWithOwnerAndRent(prop => prop.OccuId == rentId);
                // check borrower props
                return CheckProps(props);
            }
            else
            {
                // throw exception
                throw new ArgumentException();
            }
        }
        public IActionResult CheckProps(IEnumerable<Property> props)
        {
            if (props.Count() == 0)
            {
                return View("Empty");
            }
            else
            {
                return View(props);
            }
        }

        public IActionResult Create()
        {
            var propVM = new PropViewModel()
            {
                Owners = _ownerRepository.GetAll()
            };
            return View(propVM);
        }

        [HttpPost]
        public IActionResult Create(PropViewModel propViewModel)
        {
            if (!ModelState.IsValid)
            {
                propViewModel.Owners = _ownerRepository.GetAll();
                return View(propViewModel);
            }

            _propRepository.Create(propViewModel.Prop);

            return RedirectToAction("List");
        }

        public IActionResult Update(int id)
        {
            var propVM = new PropViewModel()
            {
                Prop = _propRepository.GetById(id),
                Owners = _ownerRepository.GetAll()
            };
            return View(propVM);
        }

        [HttpPost]
        public IActionResult Update(PropViewModel propViewModel)
        {
            if (!ModelState.IsValid)
            {
                propViewModel.Owners = _ownerRepository.GetAll();
                return View(propViewModel);
            }

            _propRepository.Update(propViewModel.Prop);

            return RedirectToAction("List");
        }

        public IActionResult Delete(int id)
        {
            var prop = _propRepository.GetById(id);

            _propRepository.Delete(prop);

            return RedirectToAction("List");
        }
    }
}

LibraryManagement/Views/Prop/Create.cshtml
@model PropViewModel

<div class="row orderForm">
    <form asp-controller="Prop" asp-action="Create" method="post" class="form-horizontal" role="form">
        <h3 class="col-md-offset-2">Create new property</h3>


        <div class="form-group">
            <label asp-for="Prop.Owner" class="col-md-2 control-label"></label>
            <div class="col-md-4">
                @Html.DropDownListFor(m => m.Prop.OwnerId,
                                       new SelectList(Model.Owners.Select(x => new { Value = x.OwnerId, Text = x.Name }), "Value", "Text"), "Select a owner",
                                       htmlAttributes: new { @class = "form-control border-input" })
                <span asp-validation-for="Prop.Owner" class="text-danger"></span>
            </div>

            <div class="col-md-2">
                <a class="btn btn-success" style="width:100%" asp-controller="Owner" asp-action="Create">Create a owner</a>
            </div>

        </div>
        <div class="form-group">
            <label asp-for="Prop.PName" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Prop.PName" class="form-control" placeholder="Enter property name" />
                <span asp-validation-for="Prop.PName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-6">
                <input class="btn btn-default" type="submit" value="Cancel" asp-controller="Prop" asp-action="List" />
                <input class="btn btn-success" type="submit" value="Create" />
            </div>
        </div>
    </form>
</div>

LibraryManagement/Views/Prop/Empty.cshtml
<a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Prop" asp-action="Create">Create a new property</a>

<h2>There are no properties.</h2>

LibraryManagement/Views/Prop/EmptyOwner.cshtml
@model Owner

<h2>Owner @Model.Name has no properties.</h2>

LibraryManagement/Views/Prop/List.cshtml
@model IEnumerable<Property>

<a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Prop" asp-action="Create">Create a new property</a>

<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Owners name</th>
            <th>Edit property</th>
            <th>Delete property</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Property property in Model)
        {
            <tr>
                <td>@property.PropertyId</td>
                <td>@property.PName</td>
                <td>@property.Owner.Name</td>
                <td><a class="btn btn-info" asp-area="" asp-controller="Prop" asp-action="Update" asp-route-id="@property.PropertyId">Edit</a></td>
                <td><a class="btn btn-danger" asp-area="" asp-controller="Prop" asp-action="Delete" asp-route-id="@property.PropertyId" asp-route-authorId="@ViewBag.OwnerId">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

LibraryManagement/Views/Prop/Update.cshtml
@model PropViewModel

<div class="row orderForm">

    <form asp-controller="Prop" asp-action="Update" method="post" class="form-horizontal" role="form">
        <h3 class="col-md-offset-2">Update property</h3>
        @Html.HiddenFor(m => Model.Prop.PropertyId)
        <div class="form-group">
            <label asp-for="Prop.Owner" class="col-md-2 control-label"></label>
            <div class="col-md-6">

                @Html.DropDownListFor(m => m.Prop.OwnerId,
                                                  new SelectList(Model.Owners.Select(x => new { Value = x.OwnerId, Text = x.Name }), "Value", "Text"),
                                                  htmlAttributes: new { @class = "form-control border-input" })
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Prop.PName" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Prop.PName" class="form-control" placeholder="Enter property name" />
                <span asp-validation-for="Prop.PName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-6">
                <input class="btn btn-default" type="submit" value="Cancel" asp-controller="Prop" asp-action="List" />
                <input class="btn btn-success" type="submit" value="Update" />
            </div>
        </div>
    </form>
</div>